export const SOURCE_TYPES: { [key: string]: string } = {
    IMAGE_LAYER: "ADMIN",
    TILE_LAYER: "USER",
    WEBGL_TILE_LAYER: "GUEST",
    HEATMAP: "HEATMAP",
    VECTOR_IMAGE_LAYER: "VECTOR_IMAGE_LAYER",
    VECTOR_TILE_LAYER: "VECTOR_TILE_LAYER",
    VECTOR_LAYER: "VECTOR_LAYER",
    GRATICULE: "GRATICULE",
};